### ISSUE TITLE
config file location

### ISSUE THREAD

**Issue by olegakbarov** [grammarly/omniconf#1]
> It is somewhat tricky to tell Omniconf where to look for a configuration file.

could you please elaborate on that? I have a `.edn` file in root directory of the project and it doesn't seem to be parsed.

Relevant code:

``` clj
(defn ring-init []
  (let [local-config "dev-config.edn"]
    (if (.exists (io/as-file local-config))
      (cfg/populate-from-file local-config)
      (log/warn "Can't find local dev configuration file" local-config))
    (init)))
```

**Comment by alexander-yakushev** [comment]
@olegakbarov I referred to a situation when you want to specify the confg file dynamically rather than hardcode it. In the case of hardcoding there shouldn't be any problem.

In your case, it is weird that the file is not parsed. I assume you don't get a warning, and `populate-from-file` silently finishes without making any changes?

**Comment by olegakbarov** [comment]
i got an following error:

``` bash
ERROR: [:telegram-token] : Value must be provided.
```

ofcourse `:telegram-token` exists in `dev-config.edn`, so i'm confused

Problem solves when i add default value to `(cfg/define ... )`

**Comment by alexander-yakushev** [comment]
Can you run `(cfg/populate-from-file "dev-config.edn")`, and then `(cfg/report-configuration)`? It will also help if you add another value into the file and see if it appears in the configuration. That way we'll see if the file is parsed at all.

**Comment by olegakbarov** [comment]
I'm sorry, that's my code. Wrong order of initialization.

Thanks for help and good luck with awesome library!

**Comment by alexander-yakushev** [comment]
Great to know, thank you!
