### ISSUE TITLE
SSM

### ISSUE THREAD

**Issue by devn** [grammarly/omniconf#19]
One thing that is not entirely clear in the documentation on SSM in the examples is the following:

Let's say I have an explicit mapping for an ssm-parameter, but I also want to allow that config value to be set in another manner. For example, by way of reading an edn file. What is the expected method of managing a local vs deploy config for a parameter like a db's password which will be fetched in production by way of SSM, but will be fetched via another method locally?

example:

```clojure
(cfg/define
  {:database {:nested {:password {:type :string :required true :ssm-name "/foo/bar"}}}})

(cfg/populate-from-file "config.edn")
(cfg.ssm/populate-from-ssm "/")
```

Is the expected behavior here that `populate-from-ssm` will clobber the config pulled from the `config.edn`?

**Comment by alexander-yakushev** [comment]
Judging from you closing the issue you probably have figured it out for yourself, but I'll try to answer. One way to do it is to have an option called `:env` that you set from yet another source (e.g. from ENV), and then based on its value populate either from a file or from SSM. For example:

```clj
(cfg/define
  {:env {:one-of [:local :prod]
         :default :local}
   :database {:nested {:password {:type :string :required true :ssm-name "/foo/bar"}}}})

(cfg/populate-from-env) ;; where you would have e.g. ENV=prod
(case (cfg/get :env) 
  :local (cfg/populate-from-file "config.edn")
  :prod (cfg.ssm/populate-from-ssm "/"))
