### ISSUE TITLE
Populate from properties

### ISSUE THREAD

**Issue by aksenov** [grammarly/omniconf#3]
Hi, great configuration library. I want to propose a new variant of the population: properties population (e. g. `java -Dsome.propertie="some value`").
Example:
`(populate-from-properties quit-on-error)`

**Comment by alexander-yakushev** [comment]
@aksenov Sorry this took me so long. I've implemented the tapping from Java properties, and added tests for it. Version `0.2.3` contains the feature, hope it works there!
